"use client";
import Link from "next/link";
import { usePathname,useRouter,useSearchParams } from "next/navigation";
import { useMemo,useRef,useState } from "react";
import type { MouseEvent,TouchEvent } from "react";
import { colorFamilyFromFabric } from "../lib/products";
import type { ColorFamily,Product,ProductType } from "../lib/products";

type SizeFilterKey="1"|"2"|"3"|"4"|"chaise"|"modular";
type SortKey="recommended"|"price-asc"|"price-desc"|"name-asc";
type RawFilters={type:string|null;color:string|null;seats:string|null};
type FilterState={type:ProductType|null;color:ColorFamily|null;seats:SizeFilterKey|null};
const typeOptions:{key:ProductType;label:string}[]=[{key:"corner",label:"Corner sofas"},{key:"chaise",label:"Chaise sofas"},{key:"u-shape",label:"U-shape sofas"},{key:"modular",label:"Modular sofas"},{key:"chesterfield",label:"Chesterfield"},{key:"recliner",label:"Recliner sofas"},{key:"sofa-bed",label:"Sofa beds"},{key:"cinema",label:"Cinema sofas"}];
const colorOptions:{key:ColorFamily;label:string;hex:string}[]=[{key:"ivory",label:"Ivory",hex:"#f2ede2"},{key:"beige",label:"Beige",hex:"#d9c7a8"},{key:"grey",label:"Grey",hex:"#5b6472"},{key:"green",label:"Green",hex:"#2f6f6a"},{key:"red",label:"Red",hex:"#8b1e1e"},{key:"brown",label:"Brown",hex:"#6b4a34"},{key:"blue",label:"Blue",hex:"#1f2a44"},{key:"black",label:"Black",hex:"#2b2b2d"}];
const sizeOptions:{key:SizeFilterKey;label:string;icon:string}[]=[{key:"1",label:"Armchairs",icon:"1"},{key:"2",label:"2 seater sofas",icon:"2"},{key:"3",label:"3 seater sofas",icon:"3"},{key:"4",label:"4 seater sofas",icon:"4"},{key:"chaise",label:"Chaise",icon:"L"},{key:"modular",label:"Modular",icon:"+"}];
const sortOptions:{key:SortKey;label:string}[]=[{key:"recommended",label:"Recommended"},{key:"price-asc",label:"Price: low to high"},{key:"price-desc",label:"Price: high to low"},{key:"name-asc",label:"Name: A–Z"}];
const isProductType=(v:string|null):v is ProductType=>typeOptions.some(o=>o.key===v);
const isColorFamily=(v:string|null):v is ColorFamily=>colorOptions.some(o=>o.key===v);
const isSizeFilter=(v:string|null):v is SizeFilterKey=>sizeOptions.some(o=>o.key===v);
const isSortKey=(v:string|null):v is SortKey=>sortOptions.some(o=>o.key===v);
function parseFilters(f:RawFilters):FilterState{return{type:isProductType(f.type)?f.type:null,color:isColorFamily(f.color)?f.color:null,seats:isSizeFilter(f.seats)?f.seats:null}}
function matchesSize(p:Product,s:SizeFilterKey){if(s==="chaise")return p.type==="chaise"||p.sizes?.some(o=>/chaise/i.test(o.label));if(s==="modular")return p.type==="modular";return p.seatOptions.includes(Number(s))}

function ProductCard({product,selectedColor}:{product:Product;selectedColor:ColorFamily|null}){
 const initialFabric=product.fabrics.find(f=>f.code===product.defaultFabricCode)??product.fabrics[0];
 const colorMatchedFabric=selectedColor?product.fabrics.find(f=>colorFamilyFromFabric(f)===selectedColor):null;
 const [fabricCode,setFabricCode]=useState((colorMatchedFabric??initialFabric).code);
 const touchStartRef=useRef<{x:number;y:number}|null>(null);const didSwipeRef=useRef(false);
 const selectedFabric=product.fabrics.find(f=>f.code===fabricCode)??colorMatchedFabric??initialFabric;
 const selectedIndex=Math.max(product.fabrics.findIndex(f=>f.code===selectedFabric.code),0);const hasMultipleImages=product.fabrics.length>1;
 const showAdjacentFabric=(direction:-1|1)=>{if(!hasMultipleImages)return;const next=(selectedIndex+direction+product.fabrics.length)%product.fabrics.length;const fabric=product.fabrics[next];if(fabric)setFabricCode(fabric.code)};
 const handleTouchStart=(e:TouchEvent<HTMLDivElement>)=>{const t=e.touches[0];if(!t)return;didSwipeRef.current=false;touchStartRef.current={x:t.clientX,y:t.clientY}};
 const handleTouchEnd=(e:TouchEvent<HTMLDivElement>)=>{const start=touchStartRef.current,t=e.changedTouches[0];touchStartRef.current=null;if(!start||!t||!hasMultipleImages)return;const dx=t.clientX-start.x,dy=t.clientY-start.y;if(Math.abs(dx)<42||Math.abs(dx)<Math.abs(dy)*1.2)return;didSwipeRef.current=true;showAdjacentFabric(dx<0?1:-1)};
 const handleImageClick=(e:MouseEvent<HTMLAnchorElement>)=>{if(!didSwipeRef.current)return;e.preventDefault();didSwipeRef.current=false};
 const monthly=((product.priceFromValue*.9)/48).toFixed(2);const deliveryWeeks=product.type==="corner"?"6":"7";
 return <article className="ref-product-card">
  <div className="product-image-frame ref-card-image" onTouchStart={handleTouchStart} onTouchEnd={handleTouchEnd}>
   <Link href={`/products/${product.slug}`} className="product-image" aria-label={`View ${product.name}`} onClick={handleImageClick}><img src={selectedFabric.studioFront} alt={`${product.name} in ${selectedFabric.name}`} width="750" height="520" loading="lazy" decoding="async"/></Link>
   <span className="ref-delivery-badge">▱ <b>From {deliveryWeeks} weeks</b></span>
   {hasMultipleImages&&<div className="product-image-controls"><button type="button" className="product-image-arrow prev" onClick={()=>showAdjacentFabric(-1)}>‹</button><button type="button" className="product-image-arrow next" onClick={()=>showAdjacentFabric(1)}>›</button></div>}
  </div>
  <div className="ref-card-title"><h3><Link href={`/products/${product.slug}`}>{product.name.replace(/^The /,"")}</Link></h3><button type="button" aria-label={`Add ${product.name} to favourites`}>♡</button></div>
  <p className="ref-card-tagline">{product.tagline}</p><p className="ref-card-fabric">{selectedFabric.name}</p>
  <div className="ref-card-options"><span className="ref-rainbow" aria-hidden="true"></span><span className="ref-sofa-icon" aria-hidden="true">▱</span><span>more sizes and colours available</span></div>
  <div className="ref-card-price"><strong>{product.priceFrom}</strong><i></i><b>£{monthly} per month</b></div><div className="ref-card-finance">over 4 years 10% deposit <strong>0% APR*</strong></div>
  <div className="ref-hidden-swatches" aria-label={`${product.fabrics.length} colours`}>{product.fabrics.map(f=><button type="button" key={f.code} onClick={()=>setFabricCode(f.code)} aria-label={f.name}/>)}</div>
 </article>
}

export default function ShopFilters({products,initialFilters}:{products:Product[];initialFilters:RawFilters}){
 const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams();void initialFilters;
 const [filterOpen,setFilterOpen]=useState(false),[sortOpen,setSortOpen]=useState(false);
 const urlFilters=useMemo(()=>parseFilters({type:searchParams.get("type"),color:searchParams.get("color"),seats:searchParams.get("seats")}),[searchParams]);
 const selectedType=urlFilters.type,selectedColor=urlFilters.color,selectedSize=urlFilters.seats,hasFilters=Boolean(selectedType||selectedColor||selectedSize);
 const activeFilterCount=[selectedType,selectedColor,selectedSize].filter(Boolean).length;
 const sort=isSortKey(searchParams.get("sort"))?searchParams.get("sort") as SortKey:"recommended";
 const sortLabel=sortOptions.find(o=>o.key===sort)?.label??"Recommended";
 const typeImages=useMemo(()=>Object.fromEntries(typeOptions.map(o=>{const p=products.find(i=>i.type===o.key);return[o.key,p?.heroImage??products[0]?.heroImage??""]})) as Record<ProductType,string>,[products]);
 const filteredProducts=useMemo(()=>products.filter(p=>{if(selectedType&&p.type!==selectedType)return false;if(selectedColor&&!p.colorFamilies.includes(selectedColor))return false;if(selectedSize&&!matchesSize(p,selectedSize))return false;return true}),[products,selectedType,selectedColor,selectedSize]);
 const displayedProducts=useMemo(()=>{const list=[...filteredProducts];if(sort==="price-asc")list.sort((a,b)=>a.priceFromValue-b.priceFromValue);else if(sort==="price-desc")list.sort((a,b)=>b.priceFromValue-a.priceFromValue);else if(sort==="name-asc")list.sort((a,b)=>a.name.localeCompare(b.name));return list},[filteredProducts,sort]);
 const updateParam=(key:string,value:string|null)=>{const params=new URLSearchParams(searchParams.toString());if(!value||params.get(key)===value)params.delete(key);else params.set(key,value);const q=params.toString();router.replace(q?`${pathname}?${q}`:pathname,{scroll:false})};
 const setFilter=(key:"type"|"color"|"seats",value:string)=>updateParam(key,value);
 const setSort=(value:SortKey)=>{const params=new URLSearchParams(searchParams.toString());if(value==="recommended")params.delete("sort");else params.set("sort",value);const q=params.toString();router.replace(q?`${pathname}?${q}`:pathname,{scroll:false});setSortOpen(false)};
 const clearFilters=()=>{const params=new URLSearchParams(searchParams.toString());params.delete("type");params.delete("color");params.delete("seats");const q=params.toString();router.replace(q?`${pathname}?${q}`:pathname,{scroll:false})};
 return <div className="shop-page">
  <section className="shop-filter-section" aria-labelledby="shop-by-type-title"><div className="shop-filter-heading"><h2 id="shop-by-type-title">Shop by type</h2>{hasFilters&&<button type="button" className="shop-clear" onClick={clearFilters}>Clear filters</button>}</div><div className="shop-type-grid">{typeOptions.map(o=><button type="button" className={selectedType===o.key?"shop-type-tile active":"shop-type-tile"} aria-pressed={selectedType===o.key} key={o.key} onClick={()=>setFilter("type",o.key)}><img src={typeImages[o.key]} alt="" width="320" height="220" loading="lazy"/><span>{o.label}</span></button>)}</div></section>
  <section className="shop-filter-section" aria-labelledby="shop-colour-title"><h2 id="shop-colour-title">Got a colour in mind</h2><div className="shop-colour-row">{colorOptions.map(o=><button type="button" className={selectedColor===o.key?"shop-colour active":"shop-colour"} style={{background:o.hex}} aria-label={o.label} aria-pressed={selectedColor===o.key} key={o.key} onClick={()=>setFilter("color",o.key)}/>)}</div></section>
  <section className="shop-filter-section" aria-labelledby="shop-size-title"><h2 id="shop-size-title">Got a size in mind</h2><div className="shop-size-row">{sizeOptions.map(o=><button type="button" className={selectedSize===o.key?"shop-size active":"shop-size"} aria-pressed={selectedSize===o.key} key={o.key} onClick={()=>setFilter("seats",o.key)}><span>{o.icon}</span>{o.label}</button>)}</div></section>
  <section className="shop-results" aria-labelledby="shop-results-title">
   <div className="ref-results-toolbar">
    <div className="ref-toolbar-control"><button type="button" className={filterOpen?"active":""} aria-expanded={filterOpen} onClick={()=>{setFilterOpen(v=>!v);setSortOpen(false)}}>Filter{activeFilterCount>0&&<b>{activeFilterCount}</b>} <span>☷</span></button></div>
    <div className="ref-toolbar-control"><button type="button" className={sortOpen?"active":""} aria-expanded={sortOpen} onClick={()=>{setSortOpen(v=>!v);setFilterOpen(false)}}>Sort By <small>{sortLabel}</small><span>⌄</span></button>{sortOpen&&<div className="ref-sort-menu" role="menu">{sortOptions.map(o=><button type="button" role="menuitemradio" aria-checked={sort===o.key} className={sort===o.key?"active":""} key={o.key} onClick={()=>setSort(o.key)}>{o.label}{sort===o.key&&<span>✓</span>}</button>)}</div>}</div>
   </div>
   {filterOpen&&<div className="ref-filter-panel"><div className="ref-filter-panel-head"><div><strong>Filter sofas</strong><span>{displayedProducts.length} results</span></div>{hasFilters&&<button type="button" onClick={clearFilters}>Clear all</button>}</div><div className="ref-filter-groups"><div><h3>Type</h3>{typeOptions.map(o=><button type="button" className={selectedType===o.key?"active":""} key={o.key} onClick={()=>setFilter("type",o.key)}>{o.label}<span>{selectedType===o.key?"✓":""}</span></button>)}</div><div><h3>Colour</h3>{colorOptions.map(o=><button type="button" className={selectedColor===o.key?"active":""} key={o.key} onClick={()=>setFilter("color",o.key)}><i style={{background:o.hex}}/>{o.label}<span>{selectedColor===o.key?"✓":""}</span></button>)}</div><div><h3>Size</h3>{sizeOptions.map(o=><button type="button" className={selectedSize===o.key?"active":""} key={o.key} onClick={()=>setFilter("seats",o.key)}>{o.label}<span>{selectedSize===o.key?"✓":""}</span></button>)}</div></div><button type="button" className="ref-show-results" onClick={()=>setFilterOpen(false)}>SHOW {displayedProducts.length} RESULT{displayedProducts.length===1?"":"S"}</button></div>}
   <div className="shop-results-heading"><h2 id="shop-results-title">{displayedProducts.length} matching sofa{displayedProducts.length===1?"":"s"}</h2></div>{displayedProducts.length>0?<div className="products-clone shop-products ref-product-grid">{displayedProducts.map(p=><ProductCard product={p} selectedColor={selectedColor} key={`${p.slug}-${selectedColor??"all"}`}/>)}</div>:<div className="shop-empty"><h3>No sofas match these filters</h3><p>Try removing one filter or return to the full collection.</p><button type="button" className="pill filled" onClick={clearFilters}>CLEAR FILTERS</button></div>}
  </section>
  <style jsx global>{`
   .ref-results-toolbar{max-width:1480px;margin:0 auto 20px;padding:0 28px;display:flex;gap:14px;position:relative;z-index:20}.ref-toolbar-control{position:relative}.ref-results-toolbar .ref-toolbar-control>button{min-width:160px;height:46px;border:0;border-bottom:1px solid #333;background:#fff;color:#333;display:flex;align-items:center;gap:8px;font-size:16px;padding:0;cursor:pointer}.ref-results-toolbar .ref-toolbar-control>button>span{margin-left:auto}.ref-results-toolbar .ref-toolbar-control>button>b{display:grid;place-items:center;min-width:20px;height:20px;padding:0 5px;border-radius:50%;background:#4b0b63;color:#fff;font-size:11px}.ref-results-toolbar small{font-size:11px;color:#777;white-space:nowrap}.ref-results-toolbar .ref-toolbar-control>button.active{color:#4b0b63;border-color:#4b0b63}.ref-sort-menu{position:absolute;top:52px;left:0;width:240px;background:#fff;border:1px solid #ded8db;box-shadow:0 12px 35px rgba(0,0,0,.13);padding:8px;z-index:40}.ref-sort-menu button{width:100%;border:0;background:#fff;display:flex;justify-content:space-between;align-items:center;padding:12px 10px;text-align:left;font-size:14px;cursor:pointer}.ref-sort-menu button:hover,.ref-sort-menu button.active{background:#f7f3f5;color:#4b0b63}.ref-filter-panel{max-width:1424px;margin:0 auto 30px;background:#fff;border:1px solid #e2dcdf;box-shadow:0 12px 34px rgba(0,0,0,.06);padding:24px}.ref-filter-panel-head{display:flex;justify-content:space-between;align-items:center;padding-bottom:18px;border-bottom:1px solid #ece7e9}.ref-filter-panel-head>div{display:flex;align-items:baseline;gap:12px}.ref-filter-panel-head strong{font-size:20px;color:#3f1737}.ref-filter-panel-head span{font-size:13px;color:#777}.ref-filter-panel-head>button{border:0;background:none;color:#4b0b63;text-decoration:underline;cursor:pointer}.ref-filter-groups{display:grid;grid-template-columns:repeat(3,1fr);gap:34px;padding:22px 0}.ref-filter-groups h3{font-size:15px;margin:0 0 10px;color:#343034}.ref-filter-groups>div>button{width:100%;min-height:38px;border:0;background:#fff;display:flex;align-items:center;gap:9px;padding:7px 5px;text-align:left;color:#555;cursor:pointer}.ref-filter-groups>div>button:hover,.ref-filter-groups>div>button.active{color:#4b0b63;background:#faf7f8}.ref-filter-groups>div>button>span{margin-left:auto;font-weight:700}.ref-filter-groups i{width:18px;height:18px;border-radius:50%;border:1px solid #cfc7ca;flex:0 0 auto}.ref-show-results{display:block;width:260px;height:46px;margin-left:auto;border:0;background:#4b0b63;color:#fff;font-weight:600;cursor:pointer}.shop-results-heading{display:none!important}
   .products-clone.ref-product-grid{max-width:1480px;padding:0 28px;gap:30px;grid-template-columns:repeat(4,minmax(0,1fr));align-items:start}.products-clone.ref-product-grid article.ref-product-card{text-align:left;color:#3c3b3b;min-width:0}.ref-card-image .product-image{aspect-ratio:1.54/1;background:#f3f1ed}.ref-card-image .product-image img{object-fit:cover}.ref-delivery-badge{position:absolute;right:0;bottom:0;background:#454545;color:#fff;border-radius:18px 0 0 0;padding:6px 12px;font-size:11px;display:flex;align-items:center;gap:6px}.ref-delivery-badge b{font-weight:500}.ref-card-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:17px}.products-clone.ref-product-grid .ref-card-title h3{font-family:Graphik,Arial,sans-serif;font-size:17px;line-height:1.25;color:#3d3d3d;margin:0;font-weight:500}.ref-card-title>button{border:0;background:none;font-size:25px;line-height:1;padding:0;color:#555;cursor:pointer;font-weight:300}.products-clone.ref-product-grid p.ref-card-tagline,.products-clone.ref-product-grid p.ref-card-fabric{font-size:14px;line-height:1.35;color:#555;font-weight:400;margin:7px 0 0}.products-clone.ref-product-grid p.ref-card-fabric{margin-top:5px}.ref-card-options{display:flex;align-items:center;gap:9px;margin-top:12px;font-size:13px;color:#555;white-space:nowrap}.ref-rainbow{width:18px;height:18px;border-radius:50%;background:conic-gradient(#ef3b36,#ffd83d,#46c96f,#37aaf5,#805ad5,#ef3b36);position:relative}.ref-rainbow:after{content:"";position:absolute;inset:2px;background:#fff;border-radius:50%}.ref-sofa-icon{font-size:22px;line-height:1;color:#555}.ref-card-price{display:flex;align-items:center;gap:9px;margin-top:23px;color:#444;font-size:15px;line-height:1}.ref-card-price strong,.ref-card-price b{font-weight:500}.ref-card-price i{width:1px;height:17px;background:#aaa}.ref-card-finance{font-size:11px;line-height:1.35;color:#666;margin-top:4px}.ref-card-finance strong{font-weight:700;color:#444}.ref-hidden-swatches{display:none}.ref-product-card .product-image-controls{opacity:0;display:block;transition:opacity .2s}.ref-product-card:hover .product-image-controls{opacity:1}
   @media(max-width:900px){.products-clone.ref-product-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:32px 16px;padding:0 16px}.ref-results-toolbar{padding:0 16px}.ref-filter-panel{margin:0 16px 26px}.ref-filter-groups{grid-template-columns:1fr 1fr}.ref-card-options{white-space:normal}}
   @media(max-width:560px){.products-clone.ref-product-grid{grid-template-columns:1fr 1fr;gap:28px 10px;padding:0 10px}.ref-results-toolbar{padding:0 10px;margin-bottom:18px;gap:8px}.ref-toolbar-control{width:50%}.ref-results-toolbar .ref-toolbar-control>button{width:100%;min-width:0;font-size:14px}.ref-results-toolbar small{display:none}.ref-sort-menu{left:auto;right:0;width:220px}.ref-filter-panel{margin:0 10px 22px;padding:18px 14px}.ref-filter-groups{grid-template-columns:1fr;gap:18px}.ref-show-results{width:100%;position:sticky;bottom:8px}.ref-card-title{margin-top:10px}.products-clone.ref-product-grid .ref-card-title h3{font-size:15px}.products-clone.ref-product-grid p.ref-card-tagline,.products-clone.ref-product-grid p.ref-card-fabric{font-size:12px}.ref-card-options{font-size:11px;gap:5px;margin-top:8px}.ref-rainbow{width:15px;height:15px}.ref-sofa-icon{font-size:17px}.ref-card-price{font-size:13px;margin-top:14px;gap:5px}.ref-card-finance{font-size:9px}.ref-delivery-badge{font-size:9px;padding:4px 7px}.ref-card-title>button{font-size:20px}}
  `}</style>
 </div>
}
